#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running test case'
yarn test

echo 'Styling ,testing and building project before committing.'

echo 'Code styling check pass.Trying to build now.'